### ISSUE TITLE
Plugin not working on s6

### ISSUE THREAD

**Issue by haisham** [Nexxa/cordova-base64-to-gallery#16]
throws : error while saving on samsung galaxy s6 devices (android version 6.0.1)
however works on ios platforms as well as tested on galaxy s4 and works fine
any idea?
Thx

**Comment by NiltonFelicio** [comment]
I am having the same problem with Galaxy S6

**Comment by StefanoMagrassi** [comment]
@haisham @NiltonFelicio sorry, but starting from today the project is discontinued...

Maybe you can fork the repo and try to ask some help.

Really sorry... :pensive:

**Comment by lovelyelfpop** [comment]
maybe it's a permission issue
