### ISSUE TITLE
Error while saving image

### ISSUE THREAD

**Issue by FutoRicky** [Nexxa/cordova-base64-to-gallery#19]
I'm getting the error: `Error while saving image` on android, but on iOS it works fine. Is there anything I am missing?

**Comment by addingama** [comment]
@FutoRicky how did you solve this?

**Comment by facuim** [comment]
@FutoRicky @dashracer Hey! Yesterday the plugin works great for me. But today and WITHOUT modifications. I get the same error. 
Any solution ?
