### ISSUE TITLE
Problem iOS gallery

### ISSUE THREAD

**Issue by ngt14** [Nexxa/cordova-base64-to-gallery#20]
Hi, 
I want to save photo on iOS gallery. I have success callback message "Image Saved to Gallery" but i don't there is nothing in the picture gallery

**Comment by bhlokhandwala** [comment]
Guys Even I'm also having the same problem.

**Comment by StefanoMagrassi** [comment]
@jedofus @bhlokhandwala this project is discontinued, as we wrote in the readme...

Sorry...

**Comment by rtyx** [comment]
Anyone found a solution to this?

**Comment by nicks258** [comment]
Solution??
