### ISSUE TITLE
iOS 11 crash calling base64ToGallery

### ISSUE THREAD

**Issue by mcherubin** [Nexxa/cordova-base64-to-gallery#25]
I'm using Cordova 7.0.1 (ios patform 4.4.0). After update to iOS 11 I've a crash everytime I call base64ToGallery.

Any Ideas?
Thanks

**Comment by StefanoMagrassi** [comment]
@mcherubin this project is discontinued (as I wrote in the README).

We can't help you and I suggest you to stop using this plugin and find another solution.

Sorry...

**Comment by motatoes** [comment]
I fixed the crash by opening the app in Xcode and then setting `NSPhotoLibraryAddUsageDescription` in the `plist.info` file to a string like "The app needs to access your gallery in order to save an image". It was a permission issue

**Comment by bsh314** [comment]
This behaviour can be solved by adding ios platform config into 'plist'. My pr: #26
