### ISSUE TITLE
Error while saving image / data.replace is not a function

### ISSUE THREAD

**Issue by cheeroke** [Nexxa/cordova-base64-to-gallery#27]
Hi,
I am getting `error while saving image` while trying to save image, my code is as follows:

`if (this.base64Image !== null) {
      this.base64ToGallery.base64ToGallery(this.base64Image).then(
        res => this.toast.show('P -> Saved to gallery: ' + res, '5000', 'center').subscribe(),
        err => this.toast.show('P -> Error saving to gallery: ' + err , '7000', 'center').subscribe()
      );
    }`
I am passing base64 as:
`this.base64Image = 'data:image/png;base64,' + imageData;`
where imageData is base64 string.
If i pass "imageData" only I get below error:
`data.replace is not a function`
Any idea why?
Thanks.

**Comment by remiAr** [comment]
Hello I find solution I had the same issue but now it's works you will find my function here

    takePic(){
        const options = {
            x: 0,
            y: 0,
            width: window.screen.width,
            height: window.screen.height,
            camera: CameraPreview.CAMERA_DIRECTION.FRONT, //or BACK
            toBack: true,
            tapPhoto: false,
            tapFocus: false,
            previewDrag: false,
            disableExifHeaderStripping: true
        };

        CameraPreview.startCamera(options);

        let base64option : Base64ToGalleryOptions = {
            prefix: 'img',
            mediaScanner: false
        };

    CameraPreview.takePicture({}, base64PictureData => {
        let todecode = atob(base64PictureData);

        this.base64ToGallery.base64ToGallery(btoa(todecode), base64option).then(
                res => alert('Saved image to gallery '+ JSON.stringify(res)),
                err => alert('Error saving image to gallery ' + JSON.stringify(err))
              );
        }, error =>{
            alert(JSON.stringify(error));
        });
    }

Use atob and/or btoa functions for encode and decode your picture in base64.

> this.base64Image = btoa(imageData);

Don't forget to allow storage access with AndroidPermission or in your application params.

**Comment by cheeroke** [comment]
Thanks @remiAr your code example helped me to solved my issue.
