### ISSUE TITLE
Image format

### ISSUE THREAD

**Issue by StefanoMagrassi** [Nexxa/cordova-base64-to-gallery#8]
@antonfire

> Just thinking that this will be better to give the user a choice depending on media type and best fit for minimal data transfer in mobile use. 

@agomezmoron

> Hi,
> In the fork I developed with a fork of yours (https://github.com/agomezmoron/cordova-save-image-gallery) it's supported.
> Thanks
#6

**Comment by vanessasoutoc** [comment]
which image format support?

**Comment by agomezmoron** [comment]
JPG and PNG

**Comment by StefanoMagrassi** [comment]
This project is not longer maintained and this issue is quite old... I'm gonna closing it
